export default function Tools() {
    return(
        <div>
            <h1>Skills and Tools</h1>
            <section>
                <h3>Frontend</h3>
                <ul>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>Sass</li>
                    <li>JavaScript</li>
                    <li>React</li>  
                    <li>Remix</li>
                    <li>TypeScript</li>
                    <li>Swift</li>
                </ul>
            </section>
            <section>
                <h3>Backend</h3>
                <ul>
                    <li>Node.js</li>
                    <li>Express</li>
                    <li>MongoDB</li>
                    <li>MySQL</li>
                    <li>PostgreSQL</li>
                    <li>RESTful API</li>
                    <li>Python</li>
                    <li>C# .Net 6</li>
                </ul>
            </section>
            <section>
                <h3>Design</h3>
                <ul>
                    <li>Illustrator</li>
                    <li>Photoshop</li>
                    <li>InDesign</li> 
                    <li>Figma</li>
                    <li>Canva</li>
                </ul>
            </section>
            <section>
                <h3>Tools</h3>
                <ul>
                    <li>Git</li>
                    <li>Render</li>
                    <li>Postico</li>
                    <li>Compass</li>
                    <li>Workbench</li>
                    <li>XCode</li>
                </ul>
            </section>
        </div>
    )
}